import Head from "next/head";
import styles from "../styles/Home.module.css";
import getStaticProps from "../lib/vikings";
import yamldata from "../vikings.yaml";
import jsondata from "../vikings.json";
import Vikings from "./vikings";
export default function Home() {
  const data = getStaticProps(yamldata, jsondata);
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Local Host</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Vikings />
      </main>
    </div>
  );
}
