import Head from "next/head";
import styles from "../styles/Home.module.css";
import Vikings from "./vikings";
import getVikings from "./api/getVikings";

export default function Home() {
  server.get("/api/vikings", getVikings);
  return (
    <div className={styles.container}>
      <Head>
        <title>Local Host</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Vikings />
      </main>
    </div>
  );
}
