import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import getStaticProps from "../lib/vikings";
import yamldata from "../vikings.yaml";
import jsondata from "../vikings.json";
export default function Home() {
  console.log(getStaticProps(yamldata, jsondata));
  return (
    <div className={styles.container}>
      <Head>
        <title>Local Host</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}
